name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # هر ۶ ساعت اجرا می‌شود
  workflow_dispatch: # دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # مرحله ۱: ساخت عکس مار
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mmozani
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake-dark.gif?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # مرحله ۲: آپلود عکس در برنچ output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
